# Generated by Django 5.2.3 on 2025-07-01 05:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KategoriBakteri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Bakteri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('nama_ilmiah', models.CharField(max_length=200)),
                ('bentuk', models.CharField(max_length=100)),
                ('cara_berkembang_biak', models.TextField()),
                ('gambar', models.ImageField(upload_to='gambar_bakteri/')),
                ('referensi', models.URLField()),
                ('kategori', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bakteri.kategoribakteri')),
            ],
        ),
    ]
